### ISSUE TITLE
pre-commit hook is not working

### ISSUE THREAD

**Issue by Popkornium18** [opeco17/poetry-audit-plugin#25]
The plugin works fine

```
$ poetry audit
# poetry audit report

Loading...
Scanning 55 packages...

  • black  installed 24.2.0  affected <24.3.0  CVE CVE-2024-21503

1 vulnerabilities found in 1 packages
```

However, the pre-commit hook does not:

```
$ pre-commit run poetry-audit --all-files
poetry-audit.............................................................Failed
- hook id: poetry-audit
- exit code: 1

No arguments expected for "audit" command, got "src/somepackage/run_web_server.py"

No arguments expected for "audit" command, got "src/somepackage/py.typed"

No arguments expected for "audit" command, got "src/somepackage/models.py"

No arguments expected for "audit" command, got "tests/test_somepackage.py"

No arguments expected for "audit" command, got "somepackage.service"

No arguments expected for "audit" command, got "src/somepackage/crud/binary.py"

No arguments expected for "audit" command, got "src/somepackage/routers/__init__.py"
```

I have added the hook like this:

```
repos:
  - repo: https://github.com/opeco17/poetry-audit-plugin
    rev: d110f48c48c2c4af08fab18b7c0c66d5480a6855
    hooks:
      - id: poetry-audit
```
